### ISSUE TITLE
add SlashDB SQL Pass-Thru features

### ISSUE THREAD

**Issue by mdobrzanski** [SlashDB/angular-slashdb#3]
The angular-slashdb api should support main SlashDB SQL Pass-Thru features.

Any request may be called with extension .json or header Accpet=application/json

# List available queries
http://slashdb:6543/query.json

# Get parameters
http://slashdb:6543/query/customers-in-city/city/London.json?**limit=1**
http://slashdb:6543/query/customers-in-city/city/London.json?**offset=1**
http://slashdb:6543/query/customers-in-city/city/London.json?**count** - should return header Slashdb-All-Record-Count

Test query for SQLiteChinook
```
customers-in-city:
  columns: FirstName, LastName, Phone, City, State
  creator: admin
  database: SQLiteChinook
  desc: Customer phone list by city (i.e. London)
  execute: []
  owners: [admin]
  read: []
  sqlstr: 'select {columns} from Customer where City = :city'
  write: []
```
